language: cpp

sudo: false

compiler:
  - gcc
  - clang

os:
  - linux
  - osx

env:
  - GODOT_TARGET=iphone
  - GODOT_TARGET=osx
  - GODOT_TARGET=x11
  #- GODOT_TARGET=android

matrix:
  include:
    - env: STATIC_CHECKS=yes
  exclude:
    - os: linux
      env: GODOT_TARGET=iphone
    - os: linux
      env: GODOT_TARGET=osx
    - os: linux
      env: GODOT_TARGET=android
    - os: osx
      env: GODOT_TARGET=x11
    - compiler: gcc
      env: GODOT_TARGET=iphone
    - compiler: gcc
      env: GODOT_TARGET=osx
    - compiler: clang
      env: GODOT_TARGET=android
    - compiler: clang
      env: GODOT_TARGET=x11

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty-3.9
    packages:
      - build-essential
      - scons
      - pkg-config
      - libx11-dev
      - libxcursor-dev
      - libasound2-dev
      - libfreetype6-dev
      - libgl1-mesa-dev
      - libglu1-mesa-dev
      - libssl-dev
      - libxinerama-dev
      - libxrandr-dev

      # For style checks.
      - clang-format-3.9


before_script:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update; brew install scons; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ] && [ "$GODOT_TARGET" = "android" ]; then
      brew update; brew install -v android-sdk;
      brew install -v android-ndk | grep -v "inflating:" | grep -v "creating:";
      export ANDROID_HOME=/usr/local/opt/android-sdk; export ANDROID_NDK_ROOT=/usr/local/opt/android-ndk;
    fi

script:
  - if [ "$STATIC_CHECKS" = "yes" ]; then
      sh ./misc/travis/clang-format.sh;
    else
      scons -j 2 platform=$GODOT_TARGET progress=no verbose=yes CXX=$CXX builtin_openssl=yes;
    fi
